apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: production-deployment
  template:
    metadata:
      labels:
        app: production-deployment
    spec:
      containers:
      - name: production-container
        image: us-central1-docker.pkg.dev/qwiklabs-gcp-03-fa5f252e31ad/my-repository/sample-app:v2.0
        ports:
        - containerPort: 8080
